'''
    ---------------------------------------------------------------------------
    OpenCap processing: example_sts_opensimAD_GRF.py
    ---------------------------------------------------------------------------
    Copyright 2023 Stanford University and the Authors
    Original Author(s): Antoine Falisse
    Author of Updated GRF Tracking Algorithm: Emily Miller

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    This code makes use of CasADi, which is licensed under LGPL, Version 3.0;
    https://github.com/casadi/casadi/blob/master/LICENSE.txt.

    Install requirements:
        - Visit https://github.com/stanfordnmbl/opencap-processing for details.
        - Third-party software packages:
            - Windows
                - Visual studio: https://visualstudio.microsoft.com/downloads/
                    - Make sure you install C++ support
                    - Code tested with community editions 2017-2019-2022
            - Linux
                - OpenBLAS libraries
                    - sudo apt-get install libopenblas-base

    Please contact us for any questions: https://www.opencap.ai/#contact

    This example runs a torque-driven OpenSimAD tracking simulation
    of a full sit-to-stand repetition while tracking external GRF
    and COP targets.

    This example adapts the GRF-tracking formulation developed by Emily Miller
    to a full sit-to-stand repetition. The simulation uses a torque-driven model
    and tracks externally supplied GRF and COP targets while allowing small
    penalized pelvis residual forces and moments.
'''



# %% Directories, paths, and imports. You should not need to change anything.
import os
import sys
baseDir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(baseDir)
opensimADDir = os.path.join(baseDir, 'UtilsDynamicSimulations', 'OpenSimAD')
sys.path.append(opensimADDir)

from utilsOpenSimAD import processInputsOpenSimAD, plotResultsOpenSimAD
from mainOpenSimAD import run_tracking
from utilsProcessing import getCOP_masks
from utils import storage_to_numpy

# ------------------------ USER INPUTS ---------------------------------------
# Insert your session ID here. This should be automaically generated after
# running the batchDownload.py script and should be located in the folder
# opencap-processing-grf/Data/
# If your data is somewhere else you can change the filepath in the dataFolder
#  variables below
# Insert the path to where you want the data has been downloaded.
dataFolder = os.path.join(baseDir, 'Data')
#dataFolder = 'C:\\Users\\MoBL3\\Documents\\opencap-processing-grf\\Data'

# Give the sessionID
session_id = "YOUR_SESSION_ID"

# Insert the name of the trial you want to simulate.
trial_name = 'YOUR_STS_TRIAL_NAME'

# Insert the type of activity you want to simulate
motion_type = 'sts_grf' # this will call the specific settings for GRF tracking

# Give the path to your GRF Data, automatically generated by batchDownload_ForGRFTrack.
# Prefers the foot-optimized version (_Optimized_forces.mot) if it exists,
# otherwise falls back to the plain _forces.mot name.
_force_dir = os.path.join(dataFolder, session_id, 'ForceData')
_grf_optimized = os.path.join(_force_dir, trial_name + '_Optimized_forces.mot')
_grf_plain     = os.path.join(_force_dir, trial_name + '_forces.mot')
grf_path = _grf_optimized if os.path.exists(_grf_optimized) else _grf_plain


# Full STS repetition selected by segment_STS().
repetition = 0

# STS is overground / stationary relative to the lab.
treadmill_speed = 0

# Vertical GRF threshold used to determine when COP tracking is valid.
cop_force_threshold = 10
# ------------------------ END USER INPUTS -----------------------------------
# Determine when each foot is loaded from vertical GRF.
CoP_right_mask, CoP_left_mask = getCOP_masks(
    grf_path,
    threshold=cop_force_threshold
)

# Get timestamps corresponding to the GRF/COP samples.
force_data = storage_to_numpy(grf_path)
input_times = force_data['time']


# %% Full-repetition STS hybrid simulation.
# Insert a string to "name" you case.
case = 'sts_grf_v1'


# Prepare inputs for dynamic simulation (this will be skipped if already done):
#   - Download data from OpenCap database
#   - Adjust wrapping surfaces
#   - Add foot-ground contacts
#   - Generate external function (OpenSimAD)
settings = processInputsOpenSimAD(
    baseDir,
    dataFolder,
    session_id,
    trial_name,
    motion_type,
    repetition=repetition,
    treadmill_speed=treadmill_speed)

# Add trial-specific COP validity information.
settings['CoP_mask'] = {
    'right': CoP_right_mask,
    'left': CoP_left_mask
}

settings['input_times'] = input_times

# Full-repetition STS periodic constraints are inherited from
# the sit_to_stand setup in settingsOpenSimAD.py.

# %%
# Run the dynamic simulation.
run_tracking(baseDir, dataFolder, session_id, settings, case=case)
# Plot some results.
# Comment plotResultsOpenSimAD out if running a loop to batch process data
plotResultsOpenSimAD(dataFolder, session_id, trial_name, settings, [case])
