container_image = osdf:///chtc/staging/g/gchen293/opencap.sif

executable = run_subject2_lab_sts_test.sh

log    = subject2_lab_sts_$(Cluster).log
output = subject2_lab_sts_$(Cluster).out
error  = subject2_lab_sts_$(Cluster).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = sts_open_simad_test_bundle.tar.gz, .env
transfer_output_files = subject2_lab_sts_test_results.tar.gz

request_cpus = 4
request_memory = 16GB
request_disk = 12GB

queue
